Blog/Blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('blogs.urls', 'blogs'), namespace='blogs')),
    path('users/', include('users.urls'))
]

Blog/blogs/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # 主页
    url(r'^$', views.index, name='index'),
    # 主题
    url(r'^blogs/$', views.title, name='title'),
    # 新建主题页面
    url(r'^new_blog/$', views.new_blog, name='new_blog'),
    # 编辑内容
    url(r'^blogs/(?P<blog_id>\d+)/$', views.edit_blog, name='edit_blog')
]

Blog/users/urls.py
"""为应用程序users定义URL模式"""

from django.urls import path, include

from . import views

app_name = 'users'

urlpatterns = [
    # 包含默认的身份验证URL
    path('', include('django.contrib.auth.urls')),
    # 注册页面
    path('register/', views.register, name='register'),
]

djangoProject/djangoProject/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

pie_shop/pie_shop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'', include(('pies.urls', 'pies'), namespace='piess'))
]

pie_shop/pies/urls.py
"""定义pies的URL模式"""


from django.conf.urls import url

from . import views


urlpatterns = [
    # 主页
    url(r'^$', views.index, name='index'),
    # 显示所有的馅饼
    url(r'^pies$', views.pies, name='pies'),
    # 显示单一馅饼的全部信息
    url(r'^pies/(?P<pie_id>\d+)/$', views.pie, name='pie'),
]

Blog/blogs/models.py
from django.db import models
from django.contrib.auth.models import User


class BlogPost(models.Model):
    """博客系统"""
    title = models.CharField(max_length=50)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """字符串返回"""
        return f'{self.title}'

Blog/users/models.py
from django.db import models

djangoProject/learning_log/models.py
from django.db import models

# Create your models here.

pie_shop/pies/models.py
from django.db import models


class Pie(models.Model):
    """披萨模型"""
    name = models.CharField(max_length=50)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Topping(models.Model):
    """配料"""
    pie = models.ForeignKey(Pie, on_delete=models.CASCADE)
    name = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        if len(self.name) < 30:
            return f'{self.pie}的配料：{self.name}'
        else:
            return f'{self.pie}的配料：{self.name[:30]}...'

Blog/blogs/forms.py
from django import forms

from .models import BlogPost


class BlogForm(forms.ModelForm):
    """新建表格界面"""
    class Meta:
        model = BlogPost
        fields = ['title']
        labels = {'title': ''}

Blog/blogs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import BlogPost
from .forms import BlogForm


def index(request):
    """博客主页"""
    return render(request, 'blogs/index.html')


@login_required
def title(request):
    """主题"""
    blogs = BlogPost.objects.filter(owner=request.user).order_by('date_added')
    context = {'blogs': blogs}
    return render(request, 'blogs/title.html', context)


@login_required
def new_blog(request):
    """新建主题"""
    if request.method != 'POST':
        form = BlogForm()
    else:
        form = BlogForm(data=request.POST)
        if form.is_valid():
            blog = form.save(commit=False)
            check_title_owner(request, blog)
            blog.save()
            return redirect('blogs:title')

    context = {'form': form}
    return render(request, 'blogs/new_blog.html', context)


@login_required
def edit_blog(request, blog_id):
    blog = BlogPost.objects.get(id=blog_id)
    check_title_owner(request, blog)
    if request.method != 'POST':
        form = BlogForm(instance=blog)
    else:
        form = BlogForm(instance=blog, data=request.POST)
        form.save()
        return redirect('blogs:title')

    context = {'blog': blog, 'form': form}
    return render(request, 'blogs/edit_blog.html', context)


def check_title_owner(request, blog):
    """核实用户"""
    if blog.owner != request.user:
        raise Http404

Blog/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


def register(request):
    """注册新用户"""

    if request.method != 'POST':
        # 显示空的注册表单
        form = UserCreationForm()
    else:
        # 处理填写好的表单
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            new_user.save()
            # 让用户自动登录，再重定向到主页
            login(request, new_user)

        return redirect('blogs:index')

    # 显示空表单或指出表单数据无效
    context = {'form': form}
    return render(request, 'registration/register.html', context)

djangoProject/learning_log/views.py
from django.shortcuts import render

# Create your views here.

pie_shop/pies/views.py
from django.shortcuts import render

from .models import Pie


def index(request):
    """馅饼店的主页"""
    return render(request, 'pies/index.html')


def pies(request):
    """显示所有的馅饼"""
    pies = Pie.objects.order_by('date_added')
    context = {'pies': pies}
    return render(request, 'pies/pies.html', context)


def pie(request, pie_id):
    """显示单一馅饼的全部信息"""
    pie = Pie.objects.get(id=pie_id)
    toppings = pie.topping_set.order_by('-date_added')
    context = {'pie': pie, 'toppings': toppings}
    return render(request, 'pies/pie.html', context)

Blog/blogs/templates/blogs/base.html
<a href="{% url 'blogs:index' %}">Blog index</a> -
<a href="{% url 'blogs:title' %}">Title</a> -

{% if user.is_authenticated %}
  Hello, {{ user.username }}.
  <a href="{% url 'users:logout' %}">Log out</a>
{% else %}

  <a href="{% url 'users:register' %}">Register</a> -
  <a href="{% url 'users:login' %}">Log in</a>

{% endif %}

{% block content %}

{% endblock content %}

Blog/blogs/templates/blogs/edit_blog.html
{% extends 'blogs/base.html' %}

{% block content %}

  <p>Edit blog:</p>

  <form action="{% url 'blogs:edit_blog' blog.id %}" method="post">

  {% csrf_token %}
  {{ form.as_p }}
  <button name="submit">提交修改</button>

  </form>

{% endblock content%}

Blog/blogs/templates/blogs/index.html
{% extends 'blogs/base.html' %}

{% block content %}
<p>欢迎来到blog</p>
{% endblock content%}

Blog/blogs/templates/blogs/new_blog.html
{% extends 'blogs/base.html' %}

{% block content %}

  <p>Add a new topic:</p>

  <form action="{% url 'blogs:new_blog' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">提交</button>
  </form>

{% endblock content %}

Blog/blogs/templates/blogs/title.html
{% extends 'blogs/base.html' %}

{% block content %}

  <p>题目：</p>
  <ul>
    {% for blog in blogs %}
      <li>
        <p>{{ blog.date_added|x date:'M d, Y H:i' }}</p>
        <p>{{ blog }}</p>
      </li>
      <a href="{% url 'blogs:edit_blog' blog.id %}">编辑主题</a>
    {% empty %}
      <li>没有主题</li>
    {% endfor %}
  </ul>
  <a href="{% url 'blogs:new_blog' %}">添加新主题</a>

{% endblock content %}

pie_shop/pies/templates/pies/base.html
<p>
  <a href="{% url 'piess:index' %}">欢迎来到武大郎馅饼店</a> -
  <a href="{% url 'piess:pies' %}">烧饼</a>
</p>

{% block content %}{% endblock content%}

pie_shop/pies/templates/pies/index.html
{% extends 'pies/base.html' %}

{% block content %}
  <p>客官来尝尝咋家的烧饼吧</p>
{% endblock content %}

pie_shop/pies/templates/pies/pie.html
{% extends 'pies/base.html' %}

{% block content %}

  <p>Pie: {{ pie }}</p>

  <p>Toppings:</p>
  <ul>
  {% for topping in toppings %}
    <li>
      <p>{{ topping.date_added|date:'M d, Y H:i' }}</p>
      <p>{{ topping.name|linebreaks }}</p>
    </li>
  {% empty %}
    <li>There no toppings.</li>
  {% endfor %}
  </ul>

{% endblock content %}

pie_shop/pies/templates/pies/pies.html
{% extends 'pies/base.html' %}

{% block content %}
  <ul>
  {% for pie in pies %}
    <li>
      <a href="{% url 'piess:pie' pie.id %}">{{ pie }}</a>
    </li>
  {% empty %}
    <li>No pies.</li>
  {% endfor %}
  </ul>
{% endblock content %}